function ctrlpar=ctrlparset()
ctrlpar=struct(   'Nt',8,...
                  'Nr',2,...
            'scenario','suburban_macro',...% [ urban_micro | urban_macro | urban_micro ]
           'antconfig','diversity-ant',...% ['diversity-ant'天线分集| 'closely-spaced'密置天线整列]
          'ScmOptions','none',...% ['none' | 'polarized']
          'AutoSwitch','0',... %SU/MU dynamic switching 0-off,1 on
            'maxlayer',2,...% 每个UE允许的最大传输层数
            'codesize',6,...% 码字索引的比特数
           'precoding','PEV',...% ['PEV' | 'SLNR' | 'BD' | 'RZF']
          'ebno_range',10.^(([-5:5:30])/10),...
              'ndrops',10,...
              'nusers',2,... % Number of users per cell
              'ntones',5,...
        'ntimesamples',3);